services:
  nemo:
    image: nvcr.io/nvidia/nemo:${NEMO_VERSION:-25.02}
    container_name: nemo
    volumes:
      - /home/jdn/Data/NeMo:/workspace/data
      - /home/jdn/Data/NeMoCheckpoints:/workspace/checkpoints
      - ./scripts:/workspace/scripts
    working_dir: /workspace
    ipc: host
    shm_size: 16g
    stdin_open: true
    tty: true
    profiles: ["training"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
